import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.catalog': 'Catalog',
    'nav.cart': 'Cart',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.dashboard': 'Dashboard',
    'hero.limited': 'Limited Collection',
    'hero.title': 'The Catchy Silhouette',
    'hero.cta': 'Explore New In',
    'hero.slide1.title': 'Latest Arrivals',
    'hero.slide1.subtitle': 'Fresh silhouettes for the new season',
    'hero.slide2.title': 'Exclusive Clearances',
    'hero.slide2.subtitle': 'Timeless pieces at exceptional value',
    'hero.slide3.title': 'Seasonal Edit',
    'hero.slide3.subtitle': 'Curated styles for the current atmosphere',
    'hero.slide4.title': 'New Collection',
    'hero.slide4.subtitle': 'Defining the future of silhouette',
    'featured.title': 'Featured Collections',
    'featured.subtitle': 'Curated Selection',
    'featured.headingLine1': 'Featured',
    'featured.headingLine2': 'Collections',
    'featured.viewAll': 'View All',
    'footer.about': 'About Catchy',
    'footer.aboutText': 'Crafting silhouettes that catch every eye. High-end fashion for the modern individual.',
    'footer.tagline': 'Sustainable luxury for the modern era.',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.newsletter': 'Newsletter',
    'footer.emailPlaceholder': 'Your email',
    'footer.copyright': '© 2026 Catchy Clothing.',
    'footer.shop': 'Shop',
    'footer.support': 'Support',
    'footer.contact': 'Contact Us',
    'catalog.title': 'Our Collection',
    'catalog.subtitle': 'Discover the perfect outfit for every occasion.',
    'catalog.search': 'Search products...',
    'catalog.emptyTitle': 'No pieces match',
    'catalog.emptyHint': 'Try another search or category.',
    'catalog.count': '{n} pieces',
    'catalog.shopByCategory': 'Shop by category',
    'catalog.viewCollection': 'View collection',
    'catalog.itemCount': '{n} items',
    'catalog.viewAll': 'View all products',
    'catalog.breadcrumbHome': 'Home',
    'catalog.breadcrumbCatalog': 'Browse products',
    'catalog.showingLine': 'Showing {shown} results from total {total}{for}',
    'catalog.showingForSearch': " for '{q}'",
    'catalog.sortBy': 'Sort by',
    'catalog.sortPopularity': 'Popularity',
    'catalog.sortPriceAsc': 'Price: low to high',
    'catalog.sortPriceDesc': 'Price: high to low',
    'catalog.sortName': 'Name',
    'catalog.filterCategory': 'Category',
    'catalog.filterPrice': 'Price',
    'catalog.filterSize': 'Size',
    'catalog.filterDepartment': 'Department',
    'catalog.deptWoman': 'Woman',
    'catalog.deptMen': 'Men',
    'catalog.deptKids': 'Kids',
    'catalog.deptSporty': 'Sporty',
    'catalog.deptCasual': 'Casual',
    'catalog.deptBrands': 'Brands',
    'catalog.sizeS': 'S',
    'catalog.sizeM': 'M',
    'catalog.sizeL': 'L',
    'catalog.price0_50': 'Under £50',
    'catalog.price50_100': '£50 – £100',
    'catalog.price100_150': '£100 – £150',
    'catalog.price150_plus': '£150+',
    'catalog.priceFrom': 'Min (£)',
    'catalog.priceTo': 'Max (£)',
    'catalog.priceFromPlaceholder': '0',
    'catalog.priceToPlaceholder': 'Any',
    'catalog.priceRangePill': '{min} – {max} £',
    'catalog.priceLimitPlaceholder': 'Price limit',
    'catalog.priceLimitToggle': 'Switch price filter direction',
    'catalog.priceLimitModeMax': 'Show items up to this price',
    'catalog.priceLimitModeMin': 'Show items from this price upward',
    'catalog.priceLimitPillMax': 'Up to £{n}',
    'catalog.priceLimitPillMin': 'From £{n}',
    'catalog.colorsCount': '{n} colors',
    'catalog.sale': 'Sale',
    'catalog.clearFilters': 'Clear all',
    'catalog.saleOnly': 'Discounted only',
    'catalog.loadMore': 'Load more',
    'catalog.loadingMore': 'Loading…',
    'catalog.prevPage': 'Previous',
    'catalog.nextPage': 'Next',
    'catalog.pageInfo': 'Page {page} of {pages}',
    'catalog.showingPaged': 'Showing {start}–{end} of {loaded} loaded{more}{for}',
    'catalog.moreAvailable': ' · more on server',
    'product.addToCart': 'Add to Bag',
    'product.addToShoppingBag': 'Add to Shopping Bag',
    'product.addedToBag': 'Added to Bag!',
    'product.details': 'Details',
    'product.lowStock': 'Low Stock',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.notFound': 'Product not found',
    'product.backToCatalog': 'Back to Catalog',
    'product.new': 'New',
    'product.defaultDescription':
      'Indulge in the epitome of elegance with our latest collection. This piece is designed to make you feel confident and sophisticated, no matter the occasion.',
    'product.stockAvailable': '{n} items available',
    'product.secureCheckout': 'Secure Checkout',
    'product.freeShipping': 'Free Shipping',
    'product.returns30Day': '30-Day Returns',
    'cart.emptyTitle': 'Your bag is empty',
    'cart.emptyDesc':
      "Looks like you haven't added anything to your bag yet. Explore our latest collections and find something you'll love.",
    'cart.startShopping': 'Start Shopping',
    'cart.yourSelection': 'Your Selection',
    'cart.title': 'Shopping Bag',
    'cart.itemCount': '{n} items in your bag',
    'cart.itemCountOne': '1 item in your bag',
    'cart.continueShopping': 'Continue Shopping',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.shippingFree': 'Free',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.securePayments': 'Secure Payments Guaranteed',
    'cart.close': 'Close bag',
    'cart.drawerLabel': 'Your bag',
    'cart.removeItem': 'Remove item',
    'cart.increaseQty': 'Increase quantity',
    'cart.decreaseQty': 'Decrease quantity',
    'cat.newArrivals': 'New Arrivals',
    'cat.pants': 'Pants',
    'cat.tops': 'Tops',
    'cat.dresses': 'Dresses',
    'cat.skirts': 'Skirts',
    'cat.jackets': 'Jackets',
    'cat.formal': 'Formal Sets',
    'cat.coordinates': 'Coordinates',
    'cat.all': 'All',
    'home.shopNow': 'Shop Now',
    'home.newArrivals': 'New Arrivals',
    'home.newArrivalsDesc':
      'Discover this week’s drops — refined silhouettes, premium fabrics, and pieces made to turn heads.',
    'home.filterAll': 'All',
    'home.filterDresses': 'Dresses',
    'home.filterTops': 'Tops',
    'home.filterPants': 'Pants',
    'home.testimonials': 'What Our Customers Say',
    'home.testimonialsDesc':
      'Stories from shoppers who live in Catchy — quality, fit, and service that keep them coming back.',
    'nav.sale': 'Sale',
    'nav.about': 'About',
    'nav.search': 'Search',
    'nav.searchHint': 'Type to search products',
    'nav.searchClear': 'Clear search',
    'nav.langArabic': 'AR',
    'nav.langEnglish': 'EN',
    'testimonial.1.quote':
      'The tailoring is unreal. I wore my Catchy set to an event and got compliments all night.',
    'testimonial.1.name': 'Amira K.',
    'testimonial.1.role': 'Verified buyer',
    'testimonial.2.quote':
      'Finally a brand that feels luxury without the attitude. Shipping was fast and the fabric is gorgeous.',
    'testimonial.2.name': 'Sofia M.',
    'testimonial.2.role': 'Member since 2025',
    'testimonial.3.quote':
      'I order online often — Catchy is the only shop where every piece fits the way the photos look.',
    'testimonial.3.name': 'Layla R.',
    'testimonial.3.role': 'Stylist',
    'testimonial.4.quote':
      'Beautiful packaging, thoughtful details, and a team that actually replies. Five stars.',
    'testimonial.4.name': 'Noura T.',
    'testimonial.4.role': 'Loyal customer',
    'testimonial.5.quote':
      'The green palette is so distinctive. My wardrobe feels cohesive for the first time.',
    'testimonial.5.name': 'Hana S.',
    'testimonial.5.role': 'Fashion blogger',
    'login.backToStore': 'Back to store',
    'login.welcome': 'Welcome back',
    'login.subtitle': 'Sign in with email and password, or use Google.',
    'login.fillAdmin': 'Fill demo admin credentials',
    'login.emailPlaceholder': 'Email address',
    'login.passwordPlaceholder': 'Password',
    'login.signIn': 'Sign in',
    'login.signingIn': 'Signing in…',
    'login.orContinue': 'Or continue with',
    'login.google': 'Sign in with Google',
    'login.preparing': 'Just a moment…',
    'login.signUpWelcome': 'Create your account',
    'login.signUpSubtitle': 'Register with your name, email, and password — or use Google.',
    'login.namePlaceholder': 'Full name',
    'login.nameRequired': 'Please enter your name.',
    'login.confirmPasswordPlaceholder': 'Confirm password',
    'login.signUp': 'Sign up',
    'login.signingUp': 'Creating account…',
    'login.googleSignUp': 'Sign up with Google',
    'login.switchToSignUp': "Don't have an account?",
    'login.switchToSignUpAction': 'Sign up',
    'login.switchToSignIn': 'Already have an account?',
    'login.switchToSignInAction': 'Sign in',
    'login.passwordMismatch': 'Passwords do not match.',
    'login.passwordTooShort': 'Password must be at least 6 characters.',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.catalog': 'كتالوج',
    'nav.cart': 'السلة',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.admin': 'لوحة التحكم',
    'nav.dashboard': 'لوحة التحكم',
    'hero.limited': 'مجموعة محدودة',
    'hero.title': 'خيال كاشي',
    'hero.cta': 'استكشف الجديد',
    'hero.slide1.title': 'وصلنا حديثاً',
    'hero.slide1.subtitle': 'تصاميم جديدة للموسم القادم',
    'hero.slide2.title': 'تصفيات حصرية',
    'hero.slide2.subtitle': 'قطع كلاسيكية بقيمة استثنائية',
    'hero.slide3.title': 'مختارات الموسم',
    'hero.slide3.subtitle': 'أنماط منسقة للأجواء الحالية',
    'hero.slide4.title': 'مجموعة جديدة',
    'hero.slide4.subtitle': 'تحديد مستقبل الأناقة',
    'featured.title': 'مجموعات مميزة',
    'featured.subtitle': 'اختيارات منسقة',
    'featured.headingLine1': 'مجموعات',
    'featured.headingLine2': 'مميزة',
    'featured.viewAll': 'عرض الكل',
    'footer.about': 'عن كاشي',
    'footer.aboutText': 'نصمم أزياء تخطف الأنظار. أزياء راقية للفرد العصري.',
    'footer.tagline': 'فخامة مستدامة للعصر الحديث.',
    'footer.legal': 'قانوني',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.newsletter': 'النشرة البريدية',
    'footer.emailPlaceholder': 'بريدك الإلكتروني',
    'footer.copyright': '© 2026 كاشي للملابس.',
    'footer.shop': 'تسوق',
    'footer.support': 'الدعم',
    'footer.contact': 'اتصل بنا',
    'catalog.title': 'مجموعتنا',
    'catalog.subtitle': 'اكتشف الزي المثالي لكل مناسبة.',
    'catalog.search': 'ابحث عن المنتجات...',
    'catalog.emptyTitle': 'لا توجد نتائج',
    'catalog.emptyHint': 'جرّبي كلمات أخرى أو تصنيفاً مختلفاً.',
    'catalog.count': '{n} قطعة',
    'catalog.shopByCategory': 'تسوقي حسب التصنيف',
    'catalog.viewCollection': 'عرض المجموعة',
    'catalog.itemCount': '{n} قطعة',
    'catalog.viewAll': 'كل المنتجات',
    'catalog.breadcrumbHome': 'الرئيسية',
    'catalog.breadcrumbCatalog': 'تصفح المنتجات',
    'catalog.showingLine': 'عرض {shown} من أصل {total}{for}',
    'catalog.showingForSearch': ' لـ «{q}»',
    'catalog.sortBy': 'ترتيب حسب',
    'catalog.sortPopularity': 'الأكثر شعبية',
    'catalog.sortPriceAsc': 'السعر: من الأقل',
    'catalog.sortPriceDesc': 'السعر: من الأعلى',
    'catalog.sortName': 'الاسم',
    'catalog.filterCategory': 'التصنيف',
    'catalog.filterPrice': 'السعر',
    'catalog.filterSize': 'المقاس',
    'catalog.filterDepartment': 'القسم',
    'catalog.deptWoman': 'نساء',
    'catalog.deptMen': 'رجال',
    'catalog.deptKids': 'أطفال',
    'catalog.deptSporty': 'رياضي',
    'catalog.deptCasual': 'كاجوال',
    'catalog.deptBrands': 'الماركات',
    'catalog.sizeS': 'S',
    'catalog.sizeM': 'M',
    'catalog.sizeL': 'L',
    'catalog.price0_50': 'أقل من ٥٠ £',
    'catalog.price50_100': '٥٠ – ١٠٠ £',
    'catalog.price100_150': '١٠٠ – ١٥٠ £',
    'catalog.price150_plus': 'أكثر من ١٥٠ £',
    'catalog.priceFrom': 'من (£)',
    'catalog.priceTo': 'إلى (£)',
    'catalog.priceFromPlaceholder': '٠',
    'catalog.priceToPlaceholder': 'أي سعر',
    'catalog.priceRangePill': '{min} – {max} £',
    'catalog.priceLimitPlaceholder': 'حد السعر',
    'catalog.priceLimitToggle': 'تبديل اتجاه فلتر السعر',
    'catalog.priceLimitModeMax': 'عرض المنتجات حتى هذا السعر',
    'catalog.priceLimitModeMin': 'عرض المنتجات من هذا السعر فأعلى',
    'catalog.priceLimitPillMax': 'حتى £{n}',
    'catalog.priceLimitPillMin': 'من £{n}',
    'catalog.colorsCount': '{n} ألوان',
    'catalog.sale': 'تخفيض',
    'catalog.clearFilters': 'مسح الكل',
    'catalog.saleOnly': 'تخفيضات فقط',
    'catalog.loadMore': 'تحميل المزيد',
    'catalog.loadingMore': 'جاري التحميل…',
    'catalog.prevPage': 'السابق',
    'catalog.nextPage': 'التالي',
    'catalog.pageInfo': 'صفحة {page} من {pages}',
    'catalog.showingPaged': 'عرض {start}–{end} من {loaded} محمّلة{more}{for}',
    'catalog.moreAvailable': ' · المزيد متاح',
    'product.addToCart': 'أضف للسلة',
    'product.addToShoppingBag': 'أضيفي إلى سلة التسوق',
    'product.addedToBag': 'تمت الإضافة للسلة!',
    'product.details': 'التفاصيل',
    'product.lowStock': 'كمية محدودة',
    'product.inStock': 'متوفر',
    'product.outOfStock': 'نفذت الكمية',
    'product.notFound': 'المنتج غير موجود',
    'product.backToCatalog': 'العودة للكتالوج',
    'product.new': 'جديد',
    'product.defaultDescription':
      'استمتعي بأقصى درجات الأناقة مع أحدث مجموعاتنا. قطعة مصممة لتمنحك ثقة ورقيّاً في كل مناسبة.',
    'product.stockAvailable': '{n} قطعة متوفرة',
    'product.secureCheckout': 'دفع آمن',
    'product.freeShipping': 'شحن مجاني',
    'product.returns30Day': 'إرجاع خلال 30 يوماً',
    'cart.emptyTitle': 'سلتك فارغة',
    'cart.emptyDesc':
      'لم تضيفي أي قطعة بعد. استكشفي أحدث مجموعاتنا واختاري ما يناسبك.',
    'cart.startShopping': 'ابدئي التسوق',
    'cart.yourSelection': 'اختياراتك',
    'cart.title': 'سلة التسوق',
    'cart.itemCount': '{n} قطع في سلتك',
    'cart.itemCountOne': 'قطعة واحدة في سلتك',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.orderSummary': 'ملخص الطلب',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.shippingFree': 'مجاني',
    'cart.total': 'الإجمالي',
    'cart.checkout': 'إتمام الشراء',
    'cart.securePayments': 'دفع آمن مضمون',
    'cart.close': 'إغلاق السلة',
    'cart.drawerLabel': 'سلتك',
    'cart.removeItem': 'إزالة المنتج',
    'cart.increaseQty': 'زيادة الكمية',
    'cart.decreaseQty': 'تقليل الكمية',
    'cat.newArrivals': 'وصلنا حديثاً',
    'cat.pants': 'بلاطين',
    'cat.tops': 'بلايز',
    'cat.dresses': 'فساتين',
    'cat.skirts': 'تنانير',
    'cat.jackets': 'جاكيتات',
    'cat.formal': 'طقوم رسمية',
    'cat.coordinates': 'تنسيقات',
    'cat.all': 'الكل',
    'home.shopNow': 'تسوق الآن',
    'home.newArrivals': 'وصلنا حديثاً',
    'home.newArrivalsDesc':
      'اكتشفي أحدث القطع — قصّات راقية، خامات مميزة، وتفاصيل تخطف الأنظار.',
    'home.filterAll': 'الكل',
    'home.filterDresses': 'فساتين',
    'home.filterTops': 'بلايز',
    'home.filterPants': 'بلاطين',
    'home.testimonials': 'ماذا يقول عملاؤنا',
    'home.testimonialsDesc':
      'تجارب حقيقية من يعتمدن كاشي — الجودة، المقاس، والخدمة.',
    'nav.sale': 'تخفيضات',
    'nav.about': 'من نحن',
    'nav.search': 'بحث',
    'nav.searchHint': 'ابدأ بالكتابة للبحث في المنتجات',
    'nav.searchClear': 'مسح البحث',
    'nav.langArabic': 'AR',
    'nav.langEnglish': 'EN',
    'testimonial.1.quote':
      'القصّة احترافية. ارتديت طقم كاشي في مناسبة ولم أتوقف عن المجاملات.',
    'testimonial.1.name': 'أميرة خ.',
    'testimonial.1.role': 'عميلة موثّقة',
    'testimonial.2.quote':
      'فخامة بلا تعقيد. الشحن سريع والقماش رائع.',
    'testimonial.2.name': 'صفاء م.',
    'testimonial.2.role': 'عضوة منذ 2025',
    'testimonial.3.quote':
      'أتسوق أونلاين كثيراً — كاشي الوحيدة التي يطابق المنتج الصور.',
    'testimonial.3.name': 'ليلى ر.',
    'testimonial.3.role': 'مصممة أزياء',
    'testimonial.4.quote':
      'تغليف جميل وتفاصيل مدروسة وفريق يجيب بسرعة.',
    'testimonial.4.name': 'نورة ت.',
    'testimonial.4.role': 'عميلة دائمة',
    'testimonial.5.quote':
      'ألوانكم المميزة جعلت خزانتي متناسقة لأول مرة.',
    'testimonial.5.name': 'هنا س.',
    'testimonial.5.role': 'مدونة موضة',
    'login.backToStore': 'العودة للمتجر',
    'login.welcome': 'مرحباً بعودتك',
    'login.subtitle': 'سجّل الدخول بالبريد وكلمة المرور، أو عبر Google.',
    'login.fillAdmin': 'تعبئة بيانات الإدارة التجريبية',
    'login.emailPlaceholder': 'البريد الإلكتروني',
    'login.passwordPlaceholder': 'كلمة المرور',
    'login.signIn': 'دخول',
    'login.signingIn': 'جاري تسجيل الدخول…',
    'login.orContinue': 'أو تابع عبر',
    'login.google': 'تسجيل الدخول بحساب Google',
    'login.preparing': 'لحظة…',
    'login.signUpWelcome': 'إنشاء حساب',
    'login.signUpSubtitle': 'سجّلي بالاسم والبريد وكلمة المرور — أو عبر Google.',
    'login.namePlaceholder': 'الاسم الكامل',
    'login.nameRequired': 'يرجى إدخال الاسم.',
    'login.confirmPasswordPlaceholder': 'تأكيد كلمة المرور',
    'login.signUp': 'إنشاء حساب',
    'login.signingUp': 'جاري إنشاء الحساب…',
    'login.googleSignUp': 'التسجيل بحساب Google',
    'login.switchToSignUp': 'ليس لديك حساب؟',
    'login.switchToSignUpAction': 'إنشاء حساب',
    'login.switchToSignIn': 'لديك حساب بالفعل؟',
    'login.switchToSignInAction': 'تسجيل الدخول',
    'login.passwordMismatch': 'كلمتا المرور غير متطابقتين.',
    'login.passwordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
